name: Test

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    test-php80:
        runs-on: ubuntu-20.04

        steps:
            - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                  php-version: "8.0"
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Execute tests
              run: composer test

    test-php74:
        runs-on: ubuntu-20.04

        steps:
            - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                  php-version: "7.4"
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Execute tests
              run: composer test

    test-php73:
        runs-on: ubuntu-18.04

        steps:
            - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                  php-version: "7.3"
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Execute tests
              run: composer test
